#pragma once

//#define ETL_TARGET_DEVICE_ARM
//#define ETL_TARGET_OS_NONE
#define ETL_CPP23_SUPPORTED 1
#define ETL_NO_NULLPTR_SUPPORT 0
#define ETL_NO_LARGE_CHAR_SUPPORT 0
#define ETL_CPP11_TYPE_TRAITS_IS_TRIVIAL_SUPPORTED 1


